version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api_service
    ports:
      - '3000:3000'
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: client_service
    ports:
      - '4200:4200'
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:3000/api
    restart: unless-stopped
